### ISSUE TITLE
Performance Issue in Signing

### ISSUE THREAD

**Issue by hannsjohn2007** [cisco/node-jose#212] opened 2018-08-23 07:06 UTC
Hi,

I would like to raise an issue since in our project fast response is crucial we are stuck on how to reduce the time of our response. What we want is if ever you can improve the performance of how the **Signing** works. I do time benchmark and found out that the **Signing** part takes lots of time.

This is our findings:
**Signing: 150ms-350ms
Verifying: 4ms-10ms
Encrypting: 25ms-40ms
Decrypting 15ms-25ms**

The 100ms+ is a little bit too much. Maybe you can make a little bit more faster.
I tried using a *PEM vs DER*. I also test the size Object in Buffer if that maybe matter.

**Comment by panva** [comment] 2018-08-27 09:39
@hannsjohn2007 which algs?

**Comment by jonelf** [comment] 2018-09-03 09:50
We are having the same problem and about the same execution times.

Encryption: A256GCM
Signing: RS256

Environment: AWS Lambda. Underlying hardware is rumoured to be either "3.0 GHz Intel Xeon Platinum processors with new Intel Advanced Vector Extension 512 (AVX-512) instruction set" or "High frequency Intel Xeon E5-2666 v3 (Haswell)".

**Comment by panva** [comment] 2018-09-03 09:53
@linuxwolf, I think #214 will help there. The problem is that RS currently doesnt use native crypto but forge fallback.

**Comment by panva** [comment] 2018-09-03 10:14
Can you both confirm that using #214 resolves the observed poor performance?

**Comment by jonelf** [comment] 2018-09-04 09:11
I can confirm that the RS256 signing is much faster.

**Comment by hannsjohn2007** [comment] 2018-09-10 07:45
@panva in my end its improve the the performance. hopefully changes will be reflected in the master branch.

**Comment by panva** [comment] 2018-11-05 20:55
Resolved with node-jose@1.1.0 release

**Closed by panva** 2018-11-05 20:55 UTC
